import type { Metadata } from "next";
import "./globals.css";
import Footer from "../components/layout/Footer";
import WhatsAppFloating from "@/components/ui/WhatsAppFloating";
import Navbar from "@/components/layout/Navbar";
import FloatingActions from "@/components/ui/FloatingActions";

export const metadata: Metadata = {
  title: "ROSIMO MOTOS - Domina el Asfalto y la Tierra",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body className="bg-white text-slate-900 antialiased min-h-screen">
        <Navbar />
        <main>{children}</main>
        <Footer />

        {/* El botón flotante vive aquí */}
        <WhatsAppFloating />
      </body>
    </html>
  );
}
